# Default values for malware-scanner-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: malware-scanner
namespace: malware-scanner
podLabels: {app: scanner}


replicaCount: 1

image:
  repository: asia-northeast1-docker.pkg.dev/smartcart-stagingization/staging-malware-scanner/malware-scanner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8e2e980"

service:
  name: malware-scanner-service
  type: ClusterIP
  port: 80
  targetPort: 80
  containerPort: 80
  nodePort: 8989
