# Default values for malware-scanner-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: malware-scanner
namespace: malware-scanner
podLabel: scanner
replicaCount: 2

image:
  repository: asia-northeast1-docker.pkg.dev/smartcart-stagingization/staging-malware-scanner/malware-scanner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "e55c984"

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1024Mi

service:
  name: malware-scanner-service
  type: LoadBalancer
  port: 80
  targetPort: 80
  containerName: malware-scanner-container
  containerPort: 80

gateway:
  name: http-gateway
  gatewayClassName: gke-l7-gxlb-mc

httprouter:
  name: http-router

