apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: malware-clamav-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcs-fuse-csi-pv
  storageClassName: example-storage-class