apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: malware-clamav-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: clamav-data-pv