apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: malware-clamav-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo