apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.podLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.podLabel }}
    spec:
      containers:
        - name: {{ .Values.service.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/share/clamav
              name: malware-clamav-data-pvc
      nodeSelector:
        node-type: special
      volumes:
        - name: malware-clamav-data-pvc
          persistentVolumeClaim:
            claimName: malware-clamav-data-pvc
      securityContext:
        fsGroup: 1000
