apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.podLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.podLabel }}
    spec:
      containers:
        - name: {{ .Values.service.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: malware-clamav-data-pvc
      volumes:
        - name: malware-clamav-data-pvc
          PersistentVolumeClaim:
            claimName: malware-clamav-data-pvc
