apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-pdb" .Values.deploymentName }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
