apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}
      nodePort: {{ .Values.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.podLabels }}
